return {
  almost_black   = '#1c1c1c',
  darker_grey    = '#262626',
  dark_grey      = '#303030',
  grey           = '#444444',
  medium_grey    = '#585858',
  light_grey     = '#6c6c6c',
  lighter_grey   = '#bcbcbc',
  white          = '#ffffff',
  purple         = '#5f5f87',
  light_purple   = '#8787af',
  green          = '#5f875f',
  light_green    = '#87af87',
  aqua           = '#5f8787',
  light_aqua     = '#5fafaf',
  blue           = '#5f87af',
  light_blue     = '#87afd7',
  red            = '#af5f5f',
  orange         = '#ff8700',
  ocre           = '#87875f',
  yellow         = '#ffffaf',
  DiffAdd        = '#87afff',
  DiffDelete     = '#ffdf87',
  DiffChange     = '#dfdfdf',
  DiffText       = '#afafaf',
}
